version: "3.9"

services:
  cassandra:
    build: .
    container_name: fricon
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "FeedCluster"
      CASSANDRA_DC: "dc1"
      CASSANDRA_RACK: "rack1"
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "DESCRIBE KEYSPACES"]
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  cassandra_data:
